### PR TITLE
added model, dao, service, exception, controller, html, js, for comme…

### PR DESCRIPTION
**Pull request by dwyanalford**
…nt feature.

### CODE REVIEW

**Review by EstimeB — COMMENTED** [review]
reviewed

**Review by asdarkaz1 — COMMENTED** [review]
Looks great!

**Review by asdarkaz1 — COMMENTED** [review]
Looks good!

**Review by whitmire-jonathan — APPROVED** [review]
Looks good!

**Review by asdarkaz1 — APPROVED** [review]

**Pull request merged**
